site_name: ویکی لایسنس

copyright: 'Copyright &copy; 2020 Mahdi Majidzadeh'

site_url: 'https://wikilicense.ir/'
site_author: 'Mahdi Majidzadeh'

repo_name: 'docie'
repo_url: 'https://github.com/MahdiMajidzadeh/wikilicense'

docs_dir: 'pages'
site_dir: 'docs'
lang: fa

theme:
  name: 'material'
  highlightjs: true
  # custom_dir: theme
  include_sidebar: false
  direction: 'rtl'
  language: 'fa'
  font: false
  palette:
    primary: 'deep orange'
    accent: 'cyan'

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - meta

extra_css: 
  - 'extra/style.css'  

extra:
  search:
    language: 'en, fa'

nav:
  - شروع: 'index.md'
  - پیش نیازها: 'requirement.md'